# Practical 1

In [4]:
a=17
b=155.5
c="ramya"
d=["age","name","height"]
e=(30,33)
f={"Name:","gokul"}
g={3,16,23,30}
print("age:",a,"Type:",type(a))
print("height:",b,"Type:",type(b))
print("name:",c,"Type:",type(c))
print("list:",d,"Type:",type(d))
print("tuple:",e,"Type:",type(e))
print("dictionary:",f,"Type:",type(f))
print("set:",g,"Type:",type(g))

age: 17 Type: <class 'int'>
height: 155.5 Type: <class 'float'>
name: ramya Type: <class 'str'>
list: ['age', 'name', 'height'] Type: <class 'list'>
tuple: (30, 33) Type: <class 'tuple'>
dictionary: {'gokul', 'Name:'} Type: <class 'set'>
set: {16, 3, 30, 23} Type: <class 'set'>


 # Practical 2

In [6]:
## num = int(input("Enter a number: "))
if num >= 0:
    print("The number is Positive")

n = int(input("Enter a number: "))
print("The number is Even" if n % 2 == 0 else "The number is Odd")

marks = int(input("Enter student marks: "))
if marks > 80:
    print("Grade A")
elif marks > 60:
    print("Grade B")
elif marks > 35:
    print("Grade C")
else:
    print("Fail")

user = input("Username: ")
pwd = input("Password: ")
if user == "Alice" and pwd == "1234":
    print("Login Successful")
else:
    print("Check your Credentials")
    
age = int(input("Enter your age: "))
print("Eligible to Vote" if age >= 18 else "Not Eligible")

for i in range(1, 6):
    print(i)
    
i = 1
while i <= 5:
    print(i)
    i += 1
    
for i in range(10):
    if i == 6:
        break
    print(i)

for i in range(10):
    if i == 5:
        continue
    print(i)

for i in range(10):
    if i == 5:
        pass
    else:
        print(i)

day = int(input("Enter a day (1-7): "))
match day:
    case 1:
        print("Monday")
    case 2:
        print("Tuesday")
    case 3:
        print("Wednesday")
    case 4:
        print("Thursday")
    case 5:
        print("Friday")
    case 6:
        print("Saturday")
    case 7:
        print("Sunday")
    case _:
        print("Invalid Day")

The number is Positive


Enter a number:  44


The number is Even


Enter student marks:  88


Grade A


Username:  yuvash
Password:  2009


Check your Credentials


Enter your age:  19


Eligible to Vote
1
2
3
4
5
1
2
3
4
5
0
1
2
3
4
5
0
1
2
3
4
6
7
8
9
0
1
2
3
4
6
7
8
9


Enter a day (1-7):  3


Wednesday


# Practical 3

In [1]:
def greet():
    print("Hello")
def add(a,b):
    return a+b
def multiply(a,b):
    return a*b
def welcome(name="Student"):
    print("Welcome",name)
def total(*marks):
    return sum(marks)
square=lambda x:x*x
def factorial(n):
    if n<=1:
        return 1
    return n*factorial(n-1)
greet()
print("Addition:",add(20,30))
print("Multiplication:",multiply(5,3))
welcome()
welcome("asra")
print("Total:",total(80,90,85))
print("Square:",square(5))
print("Factorial:",factorial(5))

Hello
Addition: 50
Multiplication: 15
Welcome Student
Welcome asra
Total: 255
Square: 25
Factorial: 120


# Practical 4

In [2]:
a=[1,2,3,4,5]
print("Original list:",a)
print("First:",a[0])
print("Last:",a[-1])
a.append(6)
a.insert(1,10)
a.remove(3)
print("Updated list:",a)
print("Length:",len(a))
print("Elements:")
for x in a:
    print(x)
squares=[x*x for x in a]
even=[x for x in a if x%2==0]
odd=[x for x in a if x%2!=0]
double=[x*2 for x in a]
print("Squares:",squares)
print("Even:",even)
print("Odd:",odd)
print("Double:",double)
matrix=[[1,2],[3,4]]
flat=[x for row in matrix for x in row]
print("Flattened:",flat)

Original list: [1, 2, 3, 4, 5]
First: 1
Last: 5
Updated list: [1, 10, 2, 4, 5, 6]
Length: 6
Elements:
1
10
2
4
5
6
Squares: [1, 100, 4, 16, 25, 36]
Even: [10, 2, 4, 6]
Odd: [1, 5]
Double: [2, 20, 4, 8, 10, 12]
Flattened: [1, 2, 3, 4]


# Practical 5

In [5]:
print("--------------------------------------------------------------")
print("                    TUPLE OPERATIONS                          ")
print("--------------------------------------------------------------")
t = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
print("Original tuple       :", t ,"\n")
print("First element        :", t[0])
print("Last element         :", t[-1], "\n")
l = len(t)
print("Length of the tuple :", 1, "\n")
print("Selected elements :")
print(t[3:9])
print(t[:5])
print(t[5:])
print(t[::-1])
print()
print("Count of 1            :", t.count(1), "\n")

print("Index of 7            :", t.index(7), "\n")
print("Traverse of tuple  :")
for i in t:
    print(i, end=" ")
print()
t1 = (20, 30, 40)
print("\nconcatenation of t and t1 :")
print(t + t1, "\n")
print("----------------------------------------------------")
print("                  SET OPERATIONS                    ")
print("----------------------------------------------------")
s = {10, 20, 25, 30, 40, 45, 50}
print("Original set         :", s)
print()
s.add(55)
print("Adding the element 55 :", s)
print()
s.remove(25)
print("After Removed 25      :", s)
print()
length = len(s)
print("Length of the set     :", length)
print()
print("Traverse of the set   :")
for i in s:
    print(i, end=" ")
print()
s1 = {5, 10, 15, 18, 30, 21, 48, 50, 60}
print()
print("METHOD 1")
print("Union                 :", s.union(s1))
print("Intersection          :", s.intersection(s1))
print("Difference            :", s.difference(s1))
print("Symmetric Difference  :", s.symmetric_difference(s1) , "\n")
print("METHOD 2")
print("Union                 :", s | s1)  
print("Intersection          :", s & s1)
print("Difference            :", s - s1)
print("Symmetric Difference  :", s ^ s1)

--------------------------------------------------------------
                    TUPLE OPERATIONS                          
--------------------------------------------------------------
Original tuple       : (1, 2, 3, 4, 5, 6, 7, 8, 9, 10) 

First element        : 1
Last element         : 10 

Length of the tuple : 1 

Selected elements :
(4, 5, 6, 7, 8, 9)
(1, 2, 3, 4, 5)
(6, 7, 8, 9, 10)
(10, 9, 8, 7, 6, 5, 4, 3, 2, 1)

Count of 1            : 1 

Index of 7            : 6 

Traverse of tuple  :
1 2 3 4 5 6 7 8 9 10 

concatenation of t and t1 :
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40) 

----------------------------------------------------
                  SET OPERATIONS                    
----------------------------------------------------
Original set         : {50, 20, 40, 25, 10, 45, 30}

Adding the element 55 : {50, 20, 55, 40, 25, 10, 45, 30}

After Removed 25      : {50, 20, 55, 40, 10, 45, 30}

Length of the set     : 7

Traverse of the set   :
50 20 55 40 10 45 30 

# Practical 6

In [6]:
# Create a dictionary containing student details
student={"name": "Arrahh","age":18,"course":"Python","mark":85}
print(student)

# Display the original dictionary
print("Original Dictionary:",student)

# Access and display values of specific keys
print("Name:",student["name"])
print("Age:",student["age"])

# Add a new key-value pair
student["college"]="SDNB College"
print("After adding new key:",student)

# Update the value of an existing key
student["mark"]=90
print("After updating mark:",student)

# Remove a key-value pair using pop()
student.pop("age")
print("After removing age:",student)

# Find and display the lemgth 
print("Length of dictionary:",len(student))

# Display all keys
print("Keys:",student.keys())

# Display all keys-value pairs
print("Items:",student.items())

# Traverse the dictionary using for loop
print("Key and Value:")
for key,value in student.items():
    print(key,":",value)

# Check whether a specific key exists
if "name" in student:
    print("Name key exists in the dictionary")
else:
    print("Name key does not exist")

# Create a copy of the dictionary 
student_copy=student.copy()
print("Copied Dictionary:",student_copy)

# Create another dictionary and clear all elements
another_dict={
    "name":"Rehan",
    "age":19,
    "course":"Data Science",
}
print("Another Dictionary:",another_dict)
another_dict.clear()
print("After clear():",another_dict)


# Display updated dictionaries 
print("Updated Student Dictionaries:",student)
print("Copied Dictionary:",student_copy)

{'name': 'Arrahh', 'age': 18, 'course': 'Python', 'mark': 85}
Original Dictionary: {'name': 'Arrahh', 'age': 18, 'course': 'Python', 'mark': 85}
Name: Arrahh
Age: 18
After adding new key: {'name': 'Arrahh', 'age': 18, 'course': 'Python', 'mark': 85, 'college': 'SDNB College'}
After updating mark: {'name': 'Arrahh', 'age': 18, 'course': 'Python', 'mark': 90, 'college': 'SDNB College'}
After removing age: {'name': 'Arrahh', 'course': 'Python', 'mark': 90, 'college': 'SDNB College'}
Length of dictionary: 4
Keys: dict_keys(['name', 'course', 'mark', 'college'])
Items: dict_items([('name', 'Arrahh'), ('course', 'Python'), ('mark', 90), ('college', 'SDNB College')])
Key and Value:
name : Arrahh
course : Python
mark : 90
college : SDNB College
Name key exists in the dictionary
Copied Dictionary: {'name': 'Arrahh', 'course': 'Python', 'mark': 90, 'college': 'SDNB College'}
Another Dictionary: {'name': 'Rehan', 'age': 19, 'course': 'Data Science'}
After clear(): {}
Updated Student Dictionaries:

# Practical 7

In [7]:
filename = "student.txt"
f = open(filename, "w")
print("------------------------------------------------------------")
print("             FILE CONTENTS AFTER WRITING                    ") 
print("------------------------------------------------------------")
f.write("Name        : Rose\n")
f.write("Roll No     : 12132\n")
f.write("Department  : CSE\n")
f.write("Total Marks : 519\n")
f.close()
f = open(filename, "r")
print(f.read())
f.close()
f = open(filename, "a")
f.write("Email       : abcd@gmail.com")
f.close()
print("---------------------------------------------------------")
print("              UPDATED FILE CONTENTS                      ")
print("---------------------------------------------------------")
f = open(filename,  "r")
print(f.read())
f.close()

------------------------------------------------------------
             FILE CONTENTS AFTER WRITING                    
------------------------------------------------------------
Name        : Rose
Roll No     : 12132
Department  : CSE
Total Marks : 519

---------------------------------------------------------
              UPDATED FILE CONTENTS                      
---------------------------------------------------------
Name        : Rose
Roll No     : 12132
Department  : CSE
Total Marks : 519
Email       : abcd@gmail.com


# Practical 8

In [8]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
b = np.array([2, 4, 6, 8, 10])
print("Array 1 :", a)
print("Array 2 :", a,"\n")
print("Addition         :", a + b)
print("Subtraction      :", a - b)
print("Multiplication   :", a * b)
print("Division         :", a / b,"/n")
print("First element of Array 1:", a[0])
print("Slicing arr1[1:4])       :", a[1:4], "\n")
c = np.array([1, 2, 3, 4, 5, 6])
c_reshaped = c.reshape(2, 3)
print("Reshaped 2D Array:\n", c_reshaped)
print("shape       :", c_reshaped.shape)
print("Dimension   :", c_reshaped.ndim)
print("Size        :", c_reshaped.size,"\n")
print("Sum of Array 1 :", np.sum(a))
print("Mean of Array 1 :", np.mean(a))
print("Max of Array 1 :", np.max(a))
print("Min of Array 1 :", np.min(a),"\n")
print("Square root of Array 2:", np.sqrt(b))
print("Expontential of Array 2:", np.exp(b),"\n")
arr_unsorted = np.array([50, 10, 40, 20, 30])
sorted_arr = np.sort(arr_unsorted)
print("Original array     :", arr_unsorted)
print("sorted array       :", sorted_arr)
concatenated = np.concatenate((a, b))
print("Concatenated Array:", concatenated)

Array 1 : [10 20 30 40 50]
Array 2 : [10 20 30 40 50] 

Addition         : [12 24 36 48 60]
Subtraction      : [ 8 16 24 32 40]
Multiplication   : [ 20  80 180 320 500]
Division         : [5. 5. 5. 5. 5.] /n
First element of Array 1: 10
Slicing arr1[1:4])       : [20 30 40] 

Reshaped 2D Array:
 [[1 2 3]
 [4 5 6]]
shape       : (2, 3)
Dimension   : 2
Size        : 6 

Sum of Array 1 : 150
Mean of Array 1 : 30.0
Max of Array 1 : 50
Min of Array 1 : 10 

Square root of Array 2: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Expontential of Array 2: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04] 

Original array     : [50 10 40 20 30]
sorted array       : [10 20 30 40 50]
Concatenated Array: [10 20 30 40 50  2  4  6  8 10]


# Practical 9

In [9]:
import numpy as np

# 1D array
a = np.array([10, 20, 30, 40, 50, 60])
print("Array:", a)

# Indexing
print("Indexing:", a[2])

# Slicing
print("Slicing:", a[1:4])

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", b)

# Indexing in 2D
print("Element:", b[1, 2])

# Slicing rows
print("Row:", b[0, :])

# Reshaping
c = np.array([1, 2, 3, 4, 5, 6])
print("2 x 3:\n", c.reshape(2, 3))
print("3 x 2:\n", c.reshape(3, 2))

# Flatten
print("Flatten:", c.reshape(2, 3).flatten())

# Attributes
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Size:", b.size)

Array: [10 20 30 40 50 60]
Indexing: 30
Slicing: [20 30 40]
2D Array:
 [[1 2 3]
 [4 5 6]]
Element: 6
Row: [1 2 3]
2 x 3:
 [[1 2 3]
 [4 5 6]]
3 x 2:
 [[1 2]
 [3 4]
 [5 6]]
Flatten: [1 2 3 4 5 6]
Shape: (2, 3)
Dimensions: 2
Size: 6


 # Practical 10

In [10]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print("Array:", a)
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Standard Deviation:", np.std(a))
print("Variance:", np.var(a))
print("Minimum:", np.min(a))
print("Maximum:", np.max(a))
print("Range:", np.max(a) - np.min(a))

print("25th Percentile:", np.percentile(a, 25))
print("50th Percentile:", np.percentile(a, 50))
print("75th Percentile:", np.percentile(a, 75))

print("Cumulative Sum:", np.cumsum(a))
print("Sorted Array:", np.sort(a))

Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0
Minimum: 10
Maximum: 50
Range: 40
25th Percentile: 20.0
50th Percentile: 30.0
75th Percentile: 40.0
Cumulative Sum: [ 10  30  60 100 150]
Sorted Array: [10 20 30 40 50]
